### ISSUE TITLE
Detailed steps in README; What other Atom packages for Clojure?

### ISSUE THREAD

**Issue by peter-lyons-kehl** [party-repl/clojure-repl#11]
Dear Hans @hanslivingstone and Tomomi @hitsusorisaku,

Thank you for Clojure-party-REPL.

In Vancouver, Canada we have an in-person+remote group of Clojurians. Hence Clojure-party-REPL sounds very beneficial. May I ask for help, please:

- Could you provide more detailed steps (idiot-proof) in README? As if the reader was a complete beginner with Atom. For example, I can't see "Atom's menu bar." Did you mean Ctrl+Shift+P? And more details, for example, what is it to open a file in a project? Should we open a project folder first (Application: Open Folder Ctrl+Shift+O)? I did so, and I can't start REPL:
![image](https://user-images.githubusercontent.com/4270240/48875755-b8c86280-edaf-11e8-96a0-3a5fd6abac1d.png)

- What other Atom packages would you suggest (to use, or not to use) for Clojure? We have evaluated several and didn't find any good Clojure support. Last time I tried them was in September.

Thank you for helping Clojure community.
Enjoy Thanksgiving.

**Comment by peter-lyons-kehl** [comment]
Apologies, that works.

**Comment by hitsusorisaku** [comment]
Great idea! Yeah, we're planning on adding some tutorials later, and will add more details on how to use Atom too. Thanks!

Yeah, Clojure support in Atom is still young. There's not many packages that work with Teletype yet.

I like to use one called [expand-region](https://atom.io/packages/expand-region) to help make selections easier. It's not really made for Clojure, but it works pretty well.
