### ISSUE TITLE
[Discussion] one more solution of collaborative editing

### ISSUE THREAD

**Issue by chenyong** [party-repl/clojure-repl#13]
I watched the Clojure Conf video and it really interested me. I tried to build similar environment based on my tree editor for Clojure(Script).

Keyword is **collaborative tree editing**, please checkout out the video(too long, pick the part you are interested): https://www.youtube.com/watch?v=9vgX0beDDLU&feature=youtu.be&a=

More pages to figure out details if you need:

* http://cirru.org
* https://github.com/Cirru
* https://medium.com/cirru-project
* https://www.youtube.com/playlist?list=PLyvBXLgHYHy1AIK6i5uw3_H5BIUP4CQx6

**Comment by hhc8qsed** [comment]
Hey, thanks for sharing the links. Going to close now since it's not a direct issue related to Party REPL.

**Comment by chenyong** [comment]
Found you not active on Twitter for long. It's like the only place I can reach. 🙂
