### ISSUE TITLE
The package can enter an unusable state when connecting to an nREPL server

### ISSUE THREAD

**Issue by hanslivingstone** [party-repl/clojure-repl#8]
The REPL package can be put into an unusable state where it cannot connect to any nREPL servers, until Atom is restarted.

Symptoms:
  When starting a new connection to an nREPL server, the following error will be thrown: "TypeError: Cannot read property 'constructor' of null". No connection will be made.

How to reproduce:
  1. Attempt to connect to a nREPL server that does not exist. If your nREPL server is running on port localhost:5000, try to connect on port localhost:6000. This should fail with a normal error message.

  2. Now, try connecting to a valid nREPL server say localhost:5000. Instead of connecting, the following error will be thrown: "TypeError: Cannot read property 'constructor' of null".

**Comment by hitsusorisaku** [comment]
Fixed
