### ISSUE TITLE
When pair programming, depending on the state of the Host, the Guest sometimes cannot execute code

### ISSUE THREAD

**Issue by hanslivingstone** [party-repl/clojure-repl#9]
Symptoms:
  When pairing as a Guest, usually you can type ";execute" at the end of the code to have it executed by the Host, however, sometimes the code will not be executed.

How to reproduce:
  Not sure yet. A few ideas come to mind:
  1. Maybe the REPL Entry editor needs to be active/focused on the Host? 
  2. Maybe the REPL Entry editor tab cannot be in the background?

**Comment by hanslivingstone** [comment]
@hitsusorisaku I think this is fixed now right?

**Comment by hitsusorisaku** [comment]
Yup
